# Generated by Django 2.1 on 2018-08-12 02:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('E', 'ENUM'), ('N', 'NUM'), ('T', 'TEXT'), ('D', 'DATE')], max_length=1)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Risk')),
            ],
        ),
    ]
